### ISSUE TITLE
Rename to godot-modules?

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot-modules#1]
Why the name of repository is not consistent with godot-docs?

**Comment by akien-mga** [comment]
Because it can. This issue is pointless.

**Comment by techtonik** [comment]
Is there any reason why not to have a consistent name?

**Comment by akien-mga** [comment]
Because @punto- named this repo, and I named the other one?

**Comment by adolson** [comment]
But @punto- uses a dash in his name but not in the name of this repo!?!

**Comment by techtonik** [comment]
Perhaps dash in the end is not the same as dash in the middle?

**Comment by akien-mga** [comment]
Alright, I said this issue was pointless but now that we have ``godot-docs`` and ``godot-tests``, this underscore is starting to scratch my OCD too :P

@reduz @punto- Could one of you rename the repo from the settings? (or give me access so that I do it).

**Comment by akien-mga** [comment]
OCD satisfied now that I have access to the repo settings :)
